// -----------------------------------------------------------------------------
// LawsLaboratory
// Core / Mathematics / Distributions / RealDistributions
//
// LogNormalDistribution.cs
//
// Represents a log-normal distribution.
//
// A random variable X is log-normally distributed when:
//
//     ln(X) ~ Normal(mean, standardDeviation^2)
//
// Samples are generated by first sampling the corresponding normal
// distribution and then applying the exponential transformation.
//
// Requires standardDeviation > 0.
// -----------------------------------------------------------------------------
using LawsLaboratory.Core.Mathematics.RandomGenerators;

namespace LawsLaboratory.Core.Mathematics.Distributions.RealDistributions;

    public sealed class LogNormalDistribution : IDistribution<double>
        {
        private readonly NormalDistribution _normalDistribution;

        public LogNormalDistribution(
            double mean,
            double standardDeviation,
            IRandomGenerator random)
        {
            _normalDistribution = new NormalDistribution(
                mean,
                standardDeviation,
                random);
        }

        public double Generate()
        {
            double normalValue = _normalDistribution.Generate();

            return Math.Exp(normalValue);
        }
    }
